// Generated by CoffeeScript 1.6.3
(function() {
  var fs, path;

  fs = require('fs');

  path = require('path');

  module.exports = (function(dir) {
    var dirPath, file, isFileOrDir, modulePaths, name, stats;
    modulePaths = (function() {
      var _i, _len, _ref, _results;
      _ref = fs.readdirSync(dir);
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        file = _ref[_i];
        if (file === 'index.js') {
          continue;
        }
        name = path.basename(file, '.js');
        if (name === 'test') {
          continue;
        }
        dirPath = path.join(dir, file);
        stats = fs.statSync(dirPath);
        isFileOrDir = stats.isFile() || stats.isDirectory();
        if (!isFileOrDir) {
          continue;
        }
        if (stats.isFile() && !/\.js$/.test(file)) {
          continue;
        }
        _results.push([name, dirPath]);
      }
      return _results;
    })();
    return modulePaths.reduce(function(result, pair) {
      result.__defineGetter__(pair[0], function() {
        var e;
        try {
          return require(pair[1]);
        } catch (_error) {
          e = _error;
          return void 0;
        }
      });
      return result;
    }, {});
  })(__dirname);

}).call(this);
